spring:
  application:
    name: sport-event-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/sport_event_manager
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 5000